#!/usr/bin/env bash
# generate-aliases.sh — reads locations.json and writes aliases-jump.zsh
#
# Usage:
#   ./generate-aliases.sh                  # writes to ~/.config/jump/aliases-jump.zsh
#   ./generate-aliases.sh --dry-run        # prints to stdout only
#   OUTPUT_FILE=/custom/path.zsh ./generate-aliases.sh

set -euo pipefail

# ── config ───────────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOCATIONS_FILE="${LOCATIONS_FILE:-$SCRIPT_DIR/locations.json}"
OUTPUT_FILE="${OUTPUT_FILE:-$HOME/.config/jump/aliases-jump.zsh}"
DRY_RUN=false

if [[ "${1:-}" == "--dry-run" ]]; then
  DRY_RUN=true
fi

# ── checks ───────────────────────────────────────────────────────────────────

if ! command -v jq &>/dev/null; then
  echo "ERROR: jq is not installed. Run: brew install jq" >&2
  exit 1
fi

if [[ ! -f "$LOCATIONS_FILE" ]]; then
  echo "ERROR: locations.json not found at $LOCATIONS_FILE" >&2
  exit 1
fi

# ── generate ─────────────────────────────────────────────────────────────────

TIMESTAMP="$(date '+%Y-%m-%d %H:%M')"

generate() {
  echo "# Jump Location Aliases"
  echo "# Generated by: generate-aliases.sh ($TIMESTAMP)"
  echo "# Source: $LOCATIONS_FILE"
  echo ""

  # Get unique groups in order of first appearance
  GROUPS=$(jq -r '[.locations[].group] | unique | .[]' "$LOCATIONS_FILE" 2>/dev/null || echo "")

  if [[ -z "$GROUPS" ]]; then
    # No groups — flat list
    jq -r '.locations[] | "alias \(.jump)=\"cd \(.path)\""' "$LOCATIONS_FILE"
  else
    while IFS= read -r group; do
      echo "# $group"
      jq -r --arg g "$group" \
        '.locations[] | select(.group == $g) | "alias \(.jump)=\"cd \(.path)\""' \
        "$LOCATIONS_FILE"
      echo ""
    done <<< "$GROUPS"
  fi
}

# ── output ───────────────────────────────────────────────────────────────────

if [[ "$DRY_RUN" == true ]]; then
  generate
else
  OUTPUT_DIR="$(dirname "$OUTPUT_FILE")"
  mkdir -p "$OUTPUT_DIR"
  generate > "$OUTPUT_FILE"
  echo "Aliases written to: $OUTPUT_FILE"
  echo "Run 'source $OUTPUT_FILE' or open a new terminal to activate."
fi
