#!/usr/bin/env bash
# generate-aliases.sh — reads locations.json and writes aliases-jump.zsh
#
# Usage:
#   ./generate-aliases.sh                  # writes to ~/.config/jump/aliases-jump.zsh
#   ./generate-aliases.sh --dry-run        # prints to stdout only (verify before writing)
#   OUTPUT_FILE=/custom/path.zsh ./generate-aliases.sh

set -euo pipefail

# ── config ───────────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOCATIONS_FILE="${LOCATIONS_FILE:-$SCRIPT_DIR/locations.json}"
OUTPUT_FILE="${OUTPUT_FILE:-$HOME/.config/jump/aliases-jump.zsh}"
DRY_RUN=false

if [[ "${1:-}" == "--dry-run" ]]; then
  DRY_RUN=true
fi

# ── checks ───────────────────────────────────────────────────────────────────

BASH_MAJOR="${BASH_VERSINFO[0]:-0}"
if [[ "$BASH_MAJOR" -lt 4 ]]; then
  echo "WARNING: Bash $BASH_VERSION detected. Bash 4+ recommended." >&2
  echo "Install with: brew install bash" >&2
  echo "Continuing — this script is compatible with Bash 3.2." >&2
fi

if ! command -v jq &>/dev/null; then
  echo "ERROR: jq is not installed. Run: brew install jq" >&2
  exit 1
fi

if [[ ! -f "$LOCATIONS_FILE" ]]; then
  echo "ERROR: locations.json not found at $LOCATIONS_FILE" >&2
  exit 1
fi

# ── generate (pure jq — no bash while loop, safe on Bash 3.2) ────────────────

TIMESTAMP="$(date '+%Y-%m-%d %H:%M')"

generate() {
  printf "# Jump Location Aliases\n"
  printf "# Generated by: generate-aliases.sh (%s)\n" "$TIMESTAMP"
  printf "# Source: %s\n\n" "$LOCATIONS_FILE"

  jq -r '
    .locations
    | group_by(.group)[]
    | ("# " + .[0].group),
      (.[] | "alias \(.jump)=\"cd \(.path)\""),
      ""
  ' "$LOCATIONS_FILE"
}

# ── output ───────────────────────────────────────────────────────────────────

if [[ "$DRY_RUN" == true ]]; then
  generate
else
  OUTPUT_DIR="$(dirname "$OUTPUT_FILE")"
  mkdir -p "$OUTPUT_DIR"
  generate > "$OUTPUT_FILE"

  ALIAS_COUNT=$(grep -c '^alias' "$OUTPUT_FILE" || true)
  if [[ "$ALIAS_COUNT" -eq 0 ]]; then
    echo "ERROR: Output file was written but contains no aliases. Check locations.json." >&2
    exit 1
  fi

  echo "Aliases written to: $OUTPUT_FILE ($ALIAS_COUNT aliases)"
  echo "Verify: grep '^alias' $OUTPUT_FILE"
  echo "Activate: source $OUTPUT_FILE"
fi
